// AUTO-GENERATED — run `npm run optimize:images` to regenerate
// Do not edit by hand.

export const IMAGE_DATA = {
  'doctor-lam': {
    widths: [400, 800, 1200],
    aspectRatio: 1,
    lqip: 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAUABQDASIAAhEBAxEB/8QAGQABAQADAQAAAAAAAAAAAAAAAAUBAgME/8QAHxAAAgICAQUAAAAAAAAAAAAAAAECBAMREgUxMjNB/8QAFwEAAwEAAAAAAAAAAAAAAAAAAQIDAP/EABcRAQEBAQAAAAAAAAAAAAAAAAARASH/2gAMAwEAAhEDEQA/AMOLfY4uLTKNeu8nw6ZaL1vRPtUyRLBvOHGTQCVc6clxR6bHiwBsBAse1gADP//Z',
  },
  'doctor-mak': {
    widths: [400, 800, 1200],
    aspectRatio: 1,
    lqip: 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAUABQDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAQFAv/EABsQAAIDAQEBAAAAAAAAAAAAAAABAgMhEQUU/8QAFwEAAwEAAAAAAAAAAAAAAAAAAQIDAP/EABYRAQEBAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8ApccwnafTQqqdkcOvib3hLKrLMZbjoKbaHGbQCVp+ck610uaSQBSFQWxTm8AAGf/Z',
  },
  'hero-clinic': {
    widths: [400, 800, 1200],
    aspectRatio: 1.7778,
    lqip: 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAQFA//EABwQAAICAgMAAAAAAAAAAAAAAAECAAMEIRETQf/EABYBAQEBAAAAAAAAAAAAAAAAAAMBAv/EABgRAAMBAQAAAAAAAAAAAAAAAAACERIB/9oADAMBAAIRAxEAPwC0XXyLW5KhuCZjQxK7MQzGIt0YbtBEWlpLlKgwkylj1jcJjXS5P//Z',
  },
  'location-chai-wan': {
    widths: [400, 800, 1200],
    aspectRatio: 1.2288,
    lqip: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwAAzSqMNUSyYqRGyamUroqMdS2rcUUwHiisDY//2Q==',
  },
  'service-chronic-disease': {
    widths: [400, 800, 1200],
    aspectRatio: 1,
    lqip: 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAUABQDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAQFAgb/xAAdEAADAAICAwAAAAAAAAAAAAAAAQIDEQQSEyEx/8QAFwEAAwEAAAAAAAAAAAAAAAAAAAIDBP/EABgRAQADAQAAAAAAAAAAAAAAAAABERIh/9oADAMBAAIRAxEAPwDSvJLeji1pbRmLk7e9lGPkq0kZ89XtXFU5AjJPUFckt5PHlrr9L+Hbb9sAIEr/ACUgAOH/2Q==',
  },
  'service-colorectal-screening': {
    widths: [400, 800, 1200],
    aspectRatio: 1,
    lqip: 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAUABQDASIAAhEBAxEB/8QAGAABAAMBAAAAAAAAAAAAAAAAAAQFBgL/xAAfEAACAgEEAwAAAAAAAAAAAAAAAQIDEQQFEjEUIUH/xAAWAQEBAQAAAAAAAAAAAAAAAAABAAL/xAAWEQEBAQAAAAAAAAAAAAAAAAAAEQH/2gAMAwEAAhEDEQA/AJtrnYR5aKUveC1qdVnWCQq446ARQ+C18BeOtZ6A0Rm9u1FnJLkaWmTlBZADGnQAJP/Z',
  },
  'service-dermatology': {
    widths: [400, 800, 1200],
    aspectRatio: 1,
    lqip: 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAUABQDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAIEBQP/xAAfEAADAAEDBQAAAAAAAAAAAAAAAQIDBBETBRIhMVH/xAAXAQEBAQEAAAAAAAAAAAAAAAADAgAB/8QAGBEBAQADAAAAAAAAAAAAAAAAAAECETH/2gAMAwEAAhEDEQA/AOvqKeP0ePI+zdkrVTljejNm1UJNJgZYmlRfUKimkwYrc1TYNuu6i6pzg8M5vLTt7sAq8TOrdv6AAyv/2Q==',
  },
  'service-flu-vaccine': {
    widths: [400, 800, 1200],
    aspectRatio: 1,
    lqip: 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAUABQDASIAAhEBAxEB/8QAGQABAQADAQAAAAAAAAAAAAAAAAUBAgQG/8QAHRAAAgIDAAMAAAAAAAAAAAAAAAECAwQREhQhMf/EABUBAQEAAAAAAAAAAAAAAAAAAAMC/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAERMQIDEv/aAAwDAQACEQMRAD8A9C7op62c+TfyvTJPnOctpm08hzQCUsVqEU6r3KGwToZHMdAbgOSNRJ8o7aH19AI12JnRmb1IADBI/9k=',
  },
  'service-general-practice': {
    widths: [400, 800, 1200],
    aspectRatio: 1,
    lqip: 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAUABQDASIAAhEBAxEB/8QAGAABAAMBAAAAAAAAAAAAAAAAAAIDBAX/xAAdEAACAgIDAQAAAAAAAAAAAAAAAQIDBBEFITES/8QAGAEAAgMAAAAAAAAAAAAAAAAAAQMAAgT/xAAWEQEBAQAAAAAAAAAAAAAAAAAAERL/2gAMAwEAAhEDEQA/ANVdepaNUqV8FUbYLtsjkZ0Iw0mZ8n1CVC2Dny5JJ+gEFXl2ziumcyy+xp7kAMLZXZLfoALI/9k=',
  },
  'service-voucher': {
    widths: [400, 800, 1200],
    aspectRatio: 1,
    lqip: 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAUABQDASIAAhEBAxEB/8QAGAABAAMBAAAAAAAAAAAAAAAAAAMEBQb/xAAdEAADAAICAwAAAAAAAAAAAAAAAQIDEQQxBRIh/8QAFgEBAQEAAAAAAAAAAAAAAAAAAgME/8QAGBEBAQADAAAAAAAAAAAAAAAAABECAxL/2gAMAwEAAhEDEQA/ALHGST0XXCU7MpZ1Fdl/FyFkgzxdIpTBG20wLka5fLlv37Nbx9NyvoANimDQ2AAUo//Z',
  },
} as const;

export type ImageKey = keyof typeof IMAGE_DATA;
