import type { ContentBundle } from '../types/content';

const bundle: ContentBundle = {
  announcement: {
    badge: '新',
    text: '2026年流感疫苗開始預約・歡迎致電查詢',
  },
  clinic: {
    name: '環翠綜合醫務中心',
    name_short: 'WTIMC',
    address: '香港柴灣環翠邨環翠商場1樓109號舖',
    hours: '星期一至三 09:00–13:00, 15:00–19:00・星期四・五 15:00–19:00・星期六・日 09:00–13:00',
    hours_short: '星期一至三 09:00–19:00・星期四・五 15:00–19:00・星期六・日 09:00–13:00',
    mtr: '港鐵柴灣站 B 出口・步行3分鐘',
    mtr_exit: '港鐵柴灣站 B 出口',
    bus: '巴士 8H, 8X, 82, 82X・小巴 56',
    tagline: '植根柴灣',
    hero_headline: ['家庭醫療', '位於柴灣'],
    hero_subtitle: '',
    intro: [
      '環翠綜合醫務中心紮根柴灣近二十年，由兩位資深全科醫生駐診，為環翠邨及鄰近屋苑的街坊提供全面的基層醫療服務。',
      '本診所致力以專業、親切的態度服務社區，並積極參與政府各項醫療資助計劃，讓街坊能以可負擔的費用獲得優質醫療照顧。',
    ],
    logo_alt: '環翠綜合醫務中心 標誌',
  },
  doctors: {
    mak: {
      name: '麥振威醫生',
      creds: '香港大學內外全科醫學士 (MB BS HK)',
      specialty: '全科',
      schedule: '星期四・五 下午',
      bio: '麥醫生畢業於香港大學醫學院，在公立醫院完成駐院訓練後投身社區家庭醫學。熟悉柴灣區居民的健康需要，擅長慢性病長期管理及長者健康諮詢。',
    },
    lam: {
      name: '林慧美醫生',
      creds: '香港中文大學內外全科醫學士 (MB ChB CUHK)・卡迪夫大學皮膚科文憑 (PgDip Dermatology Cardiff)',
      specialty: '全科',
      schedule: '星期一・二・三 全日・星期六上午',
      bio: '林醫生畢業於香港中文大學醫學院，其後赴英國卡迪夫大學修讀皮膚科文憑課程。除全科門診外，對濕疹、暗瘡等常見皮膚問題有豐富的診療經驗。',
    },
  },
  services: {
    gp: {
      num: '01',
      title: '全科門診',
      desc: '日常疾病診治、慢性病管理、健康諮詢及預防保健。',
      detail: '提供日常疾病診斷及治療，包括感冒、發燒、腸胃不適等常見病症。慢性病管理：定期覆診、藥物調整、健康監測。預防保健：身體檢查建議、健康諮詢、轉介服務。即日加號服務，方便街坊臨時求診。',
      tags: ['即日加號', '可預約'],
      govScheme: false,
      voucher: false,
    },
    crcsp: {
      num: '02',
      title: '大腸癌篩查計劃',
      desc: '政府資助大腸癌篩查計劃，50–75歲合資格人士可參與。',
      detail: '政府資助篩查計劃，目標群組：50–75歲無症狀香港居民。第一步：大便隱血測試 (FIT)・免費。如測試結果呈陽性，安排轉介進行大腸鏡檢查（政府資助）。早期發現可大幅提高治癒率。',
      tags: ['政府資助', '須預約'],
      govScheme: true,
      voucher: false,
    },
    cdcc: {
      num: '03',
      title: '慢性病共治計劃',
      desc: '糖尿病、高血壓共同治理先導計劃，獲政府資助。',
      detail: '政府資助先導計劃，針對糖尿病及高血壓患者。包括：定期診症、化驗檢查（HbA1c、腎功能等）、藥物治療。由家庭醫生與專科協作，減少急症室求診。符合資格者經地區康健中心轉介。',
      tags: ['政府資助', '長期跟進'],
      govScheme: true,
      voucher: false,
    },
    flu: {
      num: '04',
      title: '流感疫苗注射',
      desc: '季節性流感疫苗接種，長者及合資格人士可獲政府資助。',
      detail: '2026/27 季度流感疫苗接種服務。政府疫苗資助計劃：尚待公佈。',
      tags: ['資助計劃', '即日提供'],
      govScheme: true,
      voucher: false,
    },
    ehvs: {
      num: '05',
      title: '醫療券',
      desc: '接受長者醫療券，65歲以上長者每年享$2,000資助。',
      detail: '長者醫療券計劃：65歲或以上香港居民每年可獲 HK$2,000 醫療券資助，累積上限 HK$8,000。獎賞先導計劃：於同一年度使用 HK$1,000+ 於特定基層醫療服務，可額外獲發 HK$500。本診所已登記參與計劃，長者只需出示香港身份證即可使用。',
      tags: ['長者專享', '即時使用'],
      govScheme: false,
      voucher: true,
    },
  },
  schedule: {
    mon: { day: '星期一', am: '林慧美醫生', pm: '林慧美醫生', is_closed_am: false, is_closed_pm: false },
    tue: { day: '星期二', am: '林慧美醫生', pm: '林慧美醫生', is_closed_am: false, is_closed_pm: false },
    wed: { day: '星期三', am: '林慧美醫生', pm: '林慧美醫生', is_closed_am: false, is_closed_pm: false },
    thu: { day: '星期四', am: '— 休診', pm: '麥振威醫生', is_closed_am: true, is_closed_pm: false },
    fri: { day: '星期五', am: '— 休診', pm: '麥振威醫生', is_closed_am: true, is_closed_pm: false },
    sat: { day: '星期六', am: '林慧美醫生', pm: '— 休診', is_closed_am: false, is_closed_pm: true },
    sun: { day: '星期日及公眾假期', am: '當值醫生', pm: '— 休診', is_closed_am: false, is_closed_pm: true },
  },
  nav: {
    home: '主頁',
    services: '診所服務',
    about: '關於我們',
    contact: '聯絡我們',
  },
  pageHeros: {
    about: { eyebrow: 'ABOUT US', title: '關於我們', subtitle: '植根柴灣・服務社區' },
    services: { eyebrow: 'OUR SERVICES', title: '診所服務', subtitle: '五項專業醫療服務・三項政府資助計劃' },
    contact: { eyebrow: 'CONTACT US', title: '聯絡我們', subtitle: '歡迎致電或 WhatsApp 預約' },
  },
  contactRows: {
    address: '地址',
    transport: '交通',
    phone: '電話',
    mobile: '手機',
    email: '電郵',
    hours: '營業時間',
  },
  whatsappPrefill: '你好，我想預約診症',
  a11y: {
    menuOpen: '開啟選單',
    menuClose: '關閉選單',
    heroImageAlt: '環翠醫務中心診所實景',
    locationImageAlt: '診所實景',
  },
  meta: {
    title: '環翠綜合醫務中心 WTIMC｜柴灣家庭醫療診所｜接受醫療券',
    desc: '柴灣港鐵站旁綜合醫務中心，由兩位註冊全科醫生主理。提供全科門診、大腸癌篩查、慢性病共治、流感疫苗等政府資助計劃，接受醫療卡及長者醫療券。電話：2337 8999',
    desc_short: '柴灣港鐵站旁綜合醫務中心，由兩位註冊全科醫生主理，接受醫療卡及長者醫療券。電話：2337 8999',
  },
  ui: {
    trust: {
      insurance: '接受醫療卡',
      voucher: '長者醫療券',
      govScheme: '政府資助',
      seniorOnly: '長者專享',
      footerText: '三項政府資助計劃・歡迎街坊查詢',
    },
    trustBar: {
      insuranceEyebrow: '醫療保險',
      insuranceHeading: '接受醫療卡直付',
      insuranceDesc: '本診所接受多種私營醫療保險公司之醫療卡直付。',
      insuranceTrail: '及其他公司・致電查詢',
      voucherEyebrow: '政府資助',
      voucherHeading: '長者醫療券',
      voucherDescPre: '65歲或以上香港居民每年可獲',
      voucherDescPost: '醫療券資助，可用於本診所所有服務。',
      voucherCta: '了解使用方法',
    },
    cta: {
      call: '致電預約',
      callNow: '立即致電',
      whatsapp: 'WhatsApp 預約',
      viewDetails: '查看詳情 →',
      viewCards: '查看接受卡別',
    },
    doctors: {
      eyebrow: '醫生團隊',
      heading: '認識我們的醫生',
      headingAbout: '兩位全科醫生',
      tagline: '',
      fieldCreds: '學歷',
      fieldSpecialty: '專業範疇',
      fieldSchedule: '當值時段',
    },
    schedule: {
      eyebrow: '本週值班',
      heading: '醫生當值時間表',
      hoursEyebrow: '營業時間',
      hoursHeading: '每週應診時間',
      colDate: '日期',
      colAM: '上午 09:00–13:00',
      colPM: '下午 15:00–19:00',
      todayBadge: '今日',
      lunchLabel: '午膳：',
      lunchDetail: '每日 13:00–15:00',
      adjustNote: '如有調動，致電查詢為準',
      footerNote: '午膳 13:00–15:00・星期四・五上午及星期六下午休診',
    },
    home: {
      aboutEyebrow: '關於環翠',
      pullQuote: [
        '服務柴灣街坊近',
        '二十年',
        '由兩位註冊全科醫生主理日常診症及皮膚問題診治，',
        '並提供三項政府資助計劃，讓街坊安心就醫。',
      ],
      servicesEyebrow: '診所服務',
      servicesHeading: '我們提供的服務',
      servicesSubtitle: '三項政府資助計劃・接受長者醫療券。',
      locationEyebrow: '到訪我們',
      locationHeading: ['就在環翠邨', '港鐵站旁'],
      paymentEyebrow: '付款方式',
      paymentHeading: ['接受醫療卡及長者醫療券', '免除墊支麻煩'],
    },
    about: {
      introEyebrow: '診所簡介',
    },
    services: {
      ctaHeading: '歡迎致電預約・無須轉介',
      ctaBody: '建議於就診前致電預約，以節省輪候時間。',
    },
    contact: {
      infoEyebrow: '聯絡方式',
      paymentDesc: '歡迎致電查詢接受之醫療卡種類及醫療券使用詳情',
    },
    footer: {
      emergency: '緊急情況請致電',
      emergencyNumber: '999',
      columnTitles: { services: '服務', payment: '付款', info: '資訊' },
      footerLinks: {
        services: [
          { label: '全科', to: '/services', hash: 'service-01' },
          { label: '大腸癌篩查', to: '/services', hash: 'service-02' },
          { label: '慢性病共治', to: '/services', hash: 'service-03' },
          { label: '流感疫苗', to: '/services', hash: 'service-04' },
          { label: '醫療券', to: '/services', hash: 'service-05' },
        ],
        payment: [
          { label: '醫療卡列表', to: '/services' },
          { label: '長者醫療券', to: '/services', hash: 'service-05' },
          { label: '政府資助', to: '/services', hash: 'service-02' },
        ],
        info: [
          { label: '醫生團隊', to: '/about', hash: 'doctors' },
        ],
      },
    },
    locale: {
      toggleToEn: 'EN',
      toggleAriaLabel: 'Switch to English',
    },
  },
};

export default bundle;
