import type { ContentBundle } from '../types/content';

const bundle: ContentBundle = {
  announcement: {
    badge: 'New',
    text: '2026 Flu Vaccination now open for booking — call to enquire',
  },
  clinic: {
    name: 'Wan Tsui Integrated Medical Centre',
    name_short: 'WTIMC',
    address: 'Shop 109, 1/F, Wan Tsui Commercial Centre, Wan Tsui Estate, Chai Wan, Hong Kong',
    hours: 'Mon–Fri 09:00–13:00, 15:00–19:00 · Sat 09:00–13:00',
    hours_short: 'Mon–Fri 09:00–19:00 · Sat 09:00–13:00',
    mtr: 'MTR Chai Wan Station Exit B · 3-minute walk',
    mtr_exit: 'MTR Chai Wan Station Exit B',
    bus: 'Bus 8H, 8X, 82, 82X · Minibus 56',
    tagline: 'Rooted in Chai Wan',
    hero_headline: ['Family Medicine', 'in Chai Wan'],
    hero_subtitle: '',
    intro: [
      'Wan Tsui Integrated Medical Centre has been rooted in Chai Wan for nearly twenty years. Our two experienced general practitioners provide comprehensive primary care to residents of Wan Tsui Estate and the neighbouring estates.',
      'We are committed to serving the community with professionalism and warmth, and take part in a range of Government healthcare subsidy schemes so that residents can access quality medical care at an affordable cost.',
    ],
    logo_alt: 'Wan Tsui Integrated Medical Centre logo',
  },
  doctors: {
    mak: {
      name: 'Dr. Mak Chun Wai',
      creds: 'MB BS (HK) — Bachelor of Medicine and Bachelor of Surgery, University of Hong Kong',
      specialty: 'General Practice',
      schedule: 'Thu · Fri (all day)',
      bio: 'Dr. Mak graduated from the Faculty of Medicine of the University of Hong Kong and completed residency training in public hospitals before moving into community family medicine. Familiar with the health needs of Chai Wan residents, Dr. Mak has particular experience in long-term chronic disease management and elderly health consultations.',
    },
    lam: {
      name: 'Dr. Lam Josephine Wai May',
      creds: 'MB ChB (CUHK) · PgDip Dermatology (Cardiff)',
      specialty: 'General Practice',
      schedule: 'Mon · Tue · Wed (all day) · Sat AM',
      bio: 'Dr. Lam graduated from the Faculty of Medicine of the Chinese University of Hong Kong and later completed a postgraduate diploma in dermatology at Cardiff University in the UK. Alongside general practice, Dr. Lam has extensive experience treating common skin conditions such as eczema and acne.',
    },
  },
  services: {
    gp: {
      num: '01',
      title: 'General Practice',
      desc: 'Diagnosis and treatment of everyday illnesses, chronic disease management, health advice and preventive care.',
      detail: 'We diagnose and treat everyday illnesses, including colds, fever and digestive upsets. Chronic disease management: regular follow-up consultations, medication adjustment and health monitoring. Preventive care: health check recommendations, health advice and referral services. Same-day walk-in registration is available for residents who need to be seen at short notice.',
      tags: ['Same-day walk-in', 'Bookings welcome'],
      govScheme: false,
      voucher: false,
    },
    crcsp: {
      num: '02',
      title: 'Colorectal Cancer Screening Programme',
      desc: 'Government-subsidised colorectal cancer screening for eligible persons aged 50–75.',
      detail: 'A Government-subsidised screening programme for asymptomatic Hong Kong residents aged 50–75. Step one: Faecal Immunochemical Test (FIT) — free of charge. If the result is positive, we arrange a referral for a Government-subsidised colonoscopy. Early detection greatly improves the chance of a cure.',
      tags: ['Government-subsidised', 'Booking required'],
      govScheme: true,
      voucher: false,
    },
    cdcc: {
      num: '03',
      title: 'Chronic Disease Co-Care Pilot Scheme',
      desc: 'Government-subsidised pilot scheme for the co-management of diabetes and hypertension.',
      detail: 'A Government-subsidised pilot scheme for patients with diabetes mellitus and hypertension. It covers regular consultations, laboratory tests (HbA1c, renal function and more) and drug treatment. Family doctors work alongside specialists to reduce accident and emergency attendances. Eligible persons are referred through District Health Centres.',
      tags: ['Government-subsidised', 'Long-term follow-up'],
      govScheme: true,
      voucher: false,
    },
    flu: {
      num: '04',
      title: 'Seasonal Influenza Vaccination',
      desc: 'Seasonal flu vaccination, with Government subsidies for the elderly and other eligible persons.',
      detail: 'Seasonal influenza vaccination service for the 2026/27 season. Government Vaccination Subsidy Scheme: details to be announced.',
      tags: ['Subsidy scheme', 'Available same day'],
      govScheme: true,
      voucher: false,
    },
    ehvs: {
      num: '05',
      title: 'Elderly Health Care Voucher',
      desc: 'We accept Elderly Health Care Vouchers — HK$2,000 a year for those aged 65 or above.',
      detail: 'Elderly Health Care Voucher Scheme: Hong Kong residents aged 65 or above receive HK$2,000 in vouchers each year, with an accumulation cap of HK$8,000. Reward Pilot Scheme: spend HK$1,000 or more on designated primary healthcare services within the same year to receive an extra HK$500. This clinic is enrolled in the scheme — simply present your Hong Kong Identity Card to use your vouchers.',
      tags: ['For the elderly', 'Use immediately'],
      govScheme: false,
      voucher: true,
    },
  },
  schedule: {
    mon: { day: 'Monday', am: 'Dr. Lam', pm: 'Dr. Lam', is_closed_am: false, is_closed_pm: false },
    tue: { day: 'Tuesday', am: 'Dr. Lam', pm: 'Dr. Lam', is_closed_am: false, is_closed_pm: false },
    wed: { day: 'Wednesday', am: 'Dr. Lam', pm: 'Dr. Lam', is_closed_am: false, is_closed_pm: false },
    thu: { day: 'Thursday', am: '— Closed', pm: 'Dr. Mak', is_closed_am: true, is_closed_pm: false },
    fri: { day: 'Friday', am: 'Dr. Mak', pm: 'Dr. Mak', is_closed_am: false, is_closed_pm: false },
    sat: { day: 'Saturday', am: 'Dr. Lam', pm: '— Closed', is_closed_am: false, is_closed_pm: true },
    sun: { day: 'Sunday & Public Holidays', am: '— Closed', pm: '— Closed', is_closed_am: true, is_closed_pm: true },
  },
  nav: {
    home: 'Home',
    services: 'Services',
    about: 'About Us',
    contact: 'Contact Us',
  },
  pageHeros: {
    about: { eyebrow: 'ABOUT US', title: 'About Us', subtitle: 'Rooted in Chai Wan · Serving the community' },
    services: { eyebrow: 'OUR SERVICES', title: 'Our Services', subtitle: 'Five clinical services · Three Government-subsidised schemes' },
    contact: { eyebrow: 'CONTACT US', title: 'Contact Us', subtitle: 'Book by phone or WhatsApp' },
  },
  contactRows: {
    address: 'Address',
    transport: 'Transport',
    phone: 'Phone',
    mobile: 'Mobile',
    email: 'Email',
    hours: 'Opening Hours',
  },
  whatsappPrefill: 'Hi, I would like to book an appointment.',
  a11y: {
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    heroImageAlt: 'Wan Tsui Integrated Medical Centre clinic photo',
    locationImageAlt: 'Clinic photo',
  },
  meta: {
    title: 'Wan Tsui Integrated Medical Centre WTIMC | Family Clinic in Chai Wan | Health Care Vouchers Accepted',
    desc: 'Integrated medical centre next to Chai Wan MTR station, run by two registered general practitioners. General practice, colorectal cancer screening, Chronic Disease Co-Care and flu vaccination under Government-subsidised schemes. Insurance cards and Elderly Health Care Vouchers accepted. Tel: 2337 8999',
    desc_short: 'Integrated medical centre next to Chai Wan MTR station, run by two registered general practitioners. Insurance cards and Elderly Health Care Vouchers accepted. Tel: 2337 8999',
  },
  ui: {
    trust: {
      insurance: 'Insurance cards accepted',
      voucher: 'Elderly Health Care Voucher',
      govScheme: 'Government-subsidised',
      seniorOnly: 'For the elderly',
      footerText: 'Three Government-subsidised schemes · Enquiries welcome',
    },
    trustBar: {
      insuranceEyebrow: 'Medical insurance',
      insuranceHeading: 'Insurance cards accepted',
      insuranceDesc: 'We accept direct billing with medical cards from a wide range of private insurers.',
      insuranceTrail: 'and more · call to enquire',
      voucherEyebrow: 'Government subsidy',
      voucherHeading: 'Elderly Health Care Voucher',
      voucherDescPre: 'Hong Kong residents aged 65 or above receive ',
      voucherDescPost: ' in health care vouchers each year, usable for all services at this clinic.',
      voucherCta: 'How to use your vouchers',
    },
    cta: {
      call: 'Book by phone',
      callNow: 'Call now',
      whatsapp: 'Book on WhatsApp',
      viewDetails: 'View details →',
      viewCards: 'See accepted cards',
    },
    doctors: {
      eyebrow: 'Our doctors',
      heading: 'Meet our doctors',
      headingAbout: 'Two general practitioners',
      tagline: '',
      fieldCreds: 'Qualifications',
      fieldSpecialty: 'Specialty',
      fieldSchedule: 'Consulting hours',
    },
    schedule: {
      eyebrow: 'This week',
      heading: 'Doctor duty roster',
      hoursEyebrow: 'Opening hours',
      hoursHeading: 'Weekly consulting hours',
      colDate: 'Day',
      colAM: 'AM 09:00–13:00',
      colPM: 'PM 15:00–19:00',
      todayBadge: 'Today',
      lunchLabel: 'Lunch break: ',
      lunchDetail: 'daily 13:00–15:00',
      adjustNote: 'Schedules may change — please call to confirm',
      footerNote: 'Lunch break 13:00–15:00 · Closed on Saturday afternoons, Sundays and public holidays',
    },
    home: {
      aboutEyebrow: 'About Wan Tsui',
      pullQuote: [
        'Serving the Chai Wan community for nearly ',
        'twenty years',
        'Two registered general practitioners handle everyday consultations and common skin conditions, ',
        'with three Government-subsidised schemes so residents can seek care with confidence.',
      ],
      servicesEyebrow: 'Our services',
      servicesHeading: 'What we offer',
      servicesSubtitle: 'Three Government-subsidised schemes · Elderly Health Care Vouchers accepted.',
      locationEyebrow: 'Visit us',
      locationHeading: ['In Wan Tsui Estate', 'next to the MTR'],
      paymentEyebrow: 'Payment options',
      paymentHeading: ['Insurance cards and Health Care Vouchers accepted', 'no upfront payment hassle'],
    },
    about: {
      introEyebrow: 'About the clinic',
    },
    services: {
      ctaHeading: 'Call to book · No referral needed',
      ctaBody: 'We recommend booking by phone before your visit to reduce waiting time.',
    },
    contact: {
      infoEyebrow: 'Contact details',
      paymentDesc: 'Call us to check which medical cards we accept and how to use your health care vouchers',
    },
    footer: {
      emergency: 'In an emergency, call',
      emergencyNumber: '999',
      columnTitles: { services: 'Services', payment: 'Payment', info: 'Information' },
      footerLinks: {
        services: [
          { label: 'General Practice', to: '/services', hash: 'service-01' },
          { label: 'Colorectal Screening', to: '/services', hash: 'service-02' },
          { label: 'Chronic Disease Co-Care', to: '/services', hash: 'service-03' },
          { label: 'Flu Vaccination', to: '/services', hash: 'service-04' },
          { label: 'Health Care Voucher', to: '/services', hash: 'service-05' },
        ],
        payment: [
          { label: 'Insurance cards', to: '/services' },
          { label: 'Health Care Voucher', to: '/services', hash: 'service-05' },
          { label: 'Government-subsidised', to: '/services', hash: 'service-02' },
        ],
        info: [
          { label: 'Doctors', to: '/about', hash: 'doctors' },
        ],
      },
    },
    locale: {
      toggleToEn: '中',
      toggleAriaLabel: '切換至中文',
    },
  },
};

export default bundle;
